image: node:latest

cache:
  paths:
    - node_modules/

default:
  before_script:
    - npm install

stages:
  - linting
  - test

linting:
  stage: linting
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test