variables:
  CLI_VERSION: 8.2.0

image: trion/ng-cli-karma:${CLI_VERSION}

cache:
  paths:
    - node_modules/

default:
  before_script:
    - npm install

stages:
  - linting
  - tests
  - build-aot
  - deploy

linting:
  stage: linting
  script:
    - npm run lint

build-aot:
  stage: build-aot
  script: 
    - npm run build-aot

tests:
  stage: tests
  script:
    - npm run headlessTests

deploy:
  stage: deploy
  only: 
    - dev
  script: 
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/project-angular-gd.git
    - git push -f heroku master
