variables:
  CLI_VERSION: 8.2.0

image: trion/ng-cli-karma:${CLI_VERSION}

cache:
  paths:
    - node_modules/

default:
  before_script:
    - npm install

stages:
  - linting
  - tests

linting:
  stage: linting
  script:
    - npm run lint

tests:
  stage: tests
  script:
    - npm run headlessTests
